### ISSUE TITLE
permission errors

### ISSUE THREAD

**Issue by unknowndeira** [carmineos/fivem-handling-editor#10]
I tried many times but as I can see the permission system doesn't seem to be work.

> #Allows the members of the group admin to save server presets
> add_ace group.admin "HandlingEditor.SaveServerPreset" allow
> 
> #Allows everyone to save personal presets
> add_ace builtin.everyone "HandlingEditor.SavePersonalPreset" allow
> 
> #Allows everyone to edit the handling of a vehicle
> add_ace builtin.everyone "HandlingEditor.EditVehicle" allow

**Comment by carmineos** [comment]
Permissions aren't implemented yet, those at the moment won't do anything
