### ISSUE TITLE
Adding SubHandlingData flags doesn't work?

### ISSUE THREAD

**Issue by spcckz** [carmineos/fivem-handling-editor#11]
Hello! I'm currently trying to make a vehicle that floats on water, but i am trying to add some flags into the handling editor so i can edit them live rather than have to guess at what does what, and also to stop myself from having to re-start my game every time i want to change something. There isn't very good documentation on what these values do, But i do know that they are used in vehicles like the APC, Technical Aqua, Zhaba, And a few others to make them float. I have also managed to get it to work on a vehicle that i am making by manually adding the flags into the handling.meta of said vehicle. I'm not very satisfied in the way that it floats though, so being able to edit it live with the handling editor would be very nice.

My problem is though, when i try adding these flags to the handling editor, it removes ALL options from the handling editor aside from personal presets, server presets, and the reset button. Am i doing something wrong? Or is it just a limitation of the menu? Thanks in advance!

        <Item type="CBoatHandlingData">
          <fBoxFrontMult 
          <fBoxRearMult 
          <fBoxSideMult 
          <fSampleTop 
          <fSampleBottom 
          <fAquaplaneForce 
          <fAquaplanePushWaterMult 
          <fAquaplanePushWaterCap 
          <fAquaplanePushWaterApply 
          <fRudderForce 
          <fRudderOffsetSubmerge 
          <fRudderOffsetForce 
          <fRudderOffsetForceZMult 
          <fWaveAudioMult 
          <vecMoveResistance 
          <vecTurnResistance 
          <fLook_L_R_CamHeight 
          <fDragCoefficient 
          <fKeelSphereSize 
          <fPropRadius 
          <fLowLodAngOffset 
          <fLowLodDraughtOffset 
          <fImpellerOffset 
          <fImpellerForceMult 
          <fDinghySphereBuoyConst 
          <fProwRaiseMult 
          <fTransmissionMultiplier 
          <fTractionMultiplier 

And just for an example of how i tried adding it into the handling editor, i have attached a screenshot.
![image](https://user-images.githubusercontent.com/53491846/88892145-58d7bf80-d212-11ea-8628-19c5a239570c.png)

**Comment by carmineos** [comment]
SubHandlingData API aren't available yet in FiveM.

**Comment by spcckz** [comment]
Damnit man! Thanks anyways! ^^
